[package]
name = "day_2022_12"
version = "0.1.0"
edition = "2021"

[dependencies]
advent_of_code = { path = "../../advent_of_code" }
grid = "0.13.0"
pathfinding = "4.2.1"

[lib]
name = "puzzles"
path = "src/lib.rs"
